package:
  name: freetype
  version: 2.13.2

build:
  number: 1

source:
  url: https://download.flet.dev/freetype/freetype-2.13.2.tar.gz

patches:
  - config.patch

about:
  license_file: docs/FTL.TXT
