package:
  name: freetype
  version: 2.13.3

build:
  number: 1

source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-2.13.3.tar.gz

patches:
  - config.patch

about:
  license_file: docs/FTL.TXT
