package:
  name: pyogrio
  version: 0.10.0

requirements:
  host:
    - flet-libgdal 3.10.0
    - flet-libproj 9.5.0
    - flet-libtiff 4.7.0
    - flet-libjpeg 3.0.90
    - flet-libcurl 8.11.0
    - flet-libpsl 0.21.5
    - openssl 3.0.15

build:
  script_env:
    GDAL_VERSION: 3.10.0
    GDAL_LIBRARY_PATH: '{platlib}/opt/lib'
    GDAL_INCLUDE_PATH: '{platlib}/opt/include'
# {% if sdk != 'android' %}
    LDFLAGS: '-lproj -ltiff -ljpeg -lcurl -lpsl -lcrypto -lssl -undefined dynamic_lookup'
# {% endif %}

patches:
  - mobile.patch