package:
  name: matplotlib
  version: 3.9.0

requirements:
  host:
    - meson
    - ninja
    - numpy 2.0.0

build:
  backend-args:
    - -Csetup-args=--cross-file
    - -Csetup-args={MESON_CROSS_FILE}