package:
  name: matplotlib
  version: 3.10.0

requirements:
  build:
    - ninja
    - meson
  host:
    - numpy ^2.0.0
    - pybind11
    - flet-libjpeg 3.0.90
# {% if sdk == 'android' %}
    - flet-libcpp-shared >=27.2.12479018
# {% endif %}

build:
# {% if sdk == 'android' and arch in ['armeabi-v7a', 'x86'] %}
  script_env:
    CPPFLAGS: -Wno-c++11-narrowing
# {% endif %}
  backend-args:
    - -Csetup-args=--cross-file
    - -Csetup-args={MESON_CROSS_FILE}

# potential issues:
# https://github.com/godotengine/godot/pull/101036/files