package:
  name: matplotlib
  version: 3.9.2

requirements:
  build:
    - ninja
  host:
    - numpy ^2.0.0

build:
  backend-args:
    - -Csetup-args=--cross-file
    - -Csetup-args={MESON_CROSS_FILE}