{% set version = "1.7.1" %}

package:
  name: flet-libjq
  version: '{{ version }}'

source:
  url: https://github.com/jqlang/jq/releases/download/jq-{{ version }}/jq-{{ version }}.tar.gz

build:
  number: 10

requirements:
  build:
    - cmake

patches:
  - config.patch