image: macos-monterey

skip_branch_with_pr: true

environment:
  PYTHON_VERSION: 3.12.3
  PYTHON_SHORT_VERSION: 3.12

  matrix:
    - job_name: Build Android packages
      job_group: build_android

    - job_name: Build iOS packages
      job_group: build_ios
      APPVEYOR_BUILD_WORKER_IMAGE: macos-sonoma

    - job_name: Re-build Simple index
      job_group: rebuild_index
      job_depends_on: build_android, build_ios

stack:
- python $PYTHON_SHORT_VERSION

for:
  # ======================================
  #      Build Android packages
  # ======================================

  - matrix:
      only:
        - job_group: build_android

    environment:
      APPVEYOR_BUILD_WORKER_IMAGE: ubuntu-gce-c
      NDK_VERSION: r26d

    install:
      # use python-mobile repo to build Python for Android
      - git clone -q --branch=main https://github.com/flet-dev/python-mobile.git
      - pushd python-mobile
      - ./build-all.sh $PYTHON_VERSION
      - popd
      #- ./ci/package-python-for-android.sh python-mobile/install $PYTHON_VERSION $ANDROID_ABI
      #- find dist -type f -iname *.tar.gz -exec appveyor PushArtifact -DeploymentName python-dist-android {} \;

    build_script:
      - export PYTHON_ANDROID_SUPPORT=$(realpath ./python-mobile)
      - source ./setup.sh $PYTHON_SHORT_VERSION

      # build packages
      - forge android lru-dict:1.3.0

    test: off

  # ======================================
  #      Build Python for iOS
  # ======================================

  - matrix:
      only:
        - job_group: build_ios

    install:
      - git clone -q --branch=$PYTHON_VERSION https://github.com/flet-dev/Python-Apple-support
      - pushd Python-Apple-support
      - make
      - popd
      #- ./ci/package-python-for-ios.sh Python-Apple-support $PYTHON_VERSION
      #- find dist -type f -iname *.tar.gz -exec appveyor PushArtifact -DeploymentName python-dist-ios {} \;

    build_script:
      - export PYTHON_APPLE_SUPPORT=$(realpath ./Python-Apple-support)
      - source ./setup.sh $PYTHON_SHORT_VERSION

      # build packages
      - forge iOS lru-dict:1.3.0

    test: off

  # ======================================
  #      Rebuild Simple index
  # ======================================

  - matrix:
      only:
        - job_group: rebuild_index

    environment:
      APPVEYOR_BUILD_WORKER_IMAGE: ubuntu-gce-c

    build_script:
      - echo Rebuilding index...

    test: off
