package:
  name: shapely
  version: 2.0.6

requirements:
  host:
    - flet-libgeos 3.13.0
    - numpy ^2.0.0
# {% if sdk == 'android' %}
    - flet-libcpp-shared >=27.2.12479018
# {% endif %}

patches:
  - mobile.patch