package:
  name: lxml
  version: 5.3.0

build:
  script_env:
    WITH_XML2_CONFIG: '{platlib}/opt/bin/xml2-config'
    WITH_XSLT_CONFIG: '{platlib}/opt/bin/xslt-config'

patches:
  - mobile.patch

# {% if sdk == 'android' %}
requirements:
  host:
    - flet-libxml2 2.9.8
    - flet-libxslt 1.1.32
# {% endif %}