# {% set version = "2.15.3" %}
# {% if version.startswith('2.9.') %}
# {%   set patch = "mobile-2.9.x.patch" %}
# {% else %}
# {%   set patch = "mobile-2.15.x.patch" %}
# {% endif %}

package:
  name: flet-libxml2
  version: '{{ version }}'

build:
  number: 10

source:
  url: https://download.gnome.org/sources/libxml2/{{ version.rsplit('.', 1)[0] }}/libxml2-{{ version }}.tar.xz

patches:
  - {{ patch }}
