{% set version = "2.15.3" %}

package:
  name: flet-libxml2
  version: '{{ version }}'

source:
  url: https://download.gnome.org/sources/libxml2/{{ version.rsplit('.', 1)[0] }}/libxml2-{{ version }}.tar.xz

patches:
{% if version.startswith('2.9.') %}
  - mobile-2.9.x.patch
{% else %}
  - mobile-2.15.x.patch
{% endif %}
