package:
  name: Pillow
  version: 10.4.0

requirements:
  host:
    # PNG support is internal: libpng is not used.
    - flet-libjpeg 3.0.90
    - flet-freetype 2.13.3

patches:
  - setup.patch

# {% if sdk != 'android' %}
build:
  script_env:
    # libfreetype references both libz and libbz2
    # but doesn't link them into the static library
    LDFLAGS: -lz -lbz2
# {% endif %}