package:
  name: Pillow
  version: 10.4.0

requirements:
  host:
    # PNG support is internal: libpng is not used.
    - libjpeg
    - freetype

patches:
  - setup.patch

build:
  script_env:
    # libfreetype references both libz and libbz2
    # but doesn't link them into the static library
    LDFLAGS: -lz -lbz2