#
# Autogenerated by Thrift Compiler (0.25.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
all_structs = []


class Iface(object):
    def submit(self, readings):
        """
        Parameters:
         - readings

        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def submit(self, readings):
        """
        Parameters:
         - readings

        """
        self.send_submit(readings)
        return self.recv_submit()

    def send_submit(self, readings):
        self._oprot.writeMessageBegin('submit', TMessageType.CALL, self._seqid)
        args = submit_args()
        args.readings = readings
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_submit(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = submit_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.invalid is not None:
            raise result.invalid
        raise TApplicationException(TApplicationException.MISSING_RESULT, "submit failed: unknown result")


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["submit"] = Processor.process_submit
        self._on_message_begin = None

    def on_message_begin(self, func):
        self._on_message_begin = func

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if self._on_message_begin:
            self._on_message_begin(name, type, seqid)
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_submit(self, seqid, iprot, oprot):
        args = submit_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = submit_result()
        try:
            result.success = self._handler.submit(args.readings)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except InvalidReading as invalid:
            msg_type = TMessageType.REPLY
            result.invalid = invalid
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("submit", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class submit_args(object):
    """
    Attributes:
     - readings

    """
    thrift_spec = None


    def __init__(self, readings = None,):
        self.readings = readings

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.increment_recursion_depth()
        try:
            iprot.readStructBegin()
            while True:
                (fname, ftype, fid) = iprot.readFieldBegin()
                if ftype == TType.STOP:
                    break
                if fid == 1:
                    if ftype == TType.LIST:
                        self.readings = []
                        (_etype19, _size16) = iprot.readListBegin()
                        for _i20 in range(_size16):
                            _elem21 = Reading()
                            _elem21.read(iprot)
                            self.readings.append(_elem21)
                        iprot.readListEnd()
                    else:
                        iprot.skip(ftype)
                else:
                    iprot.skip(ftype)
                iprot.readFieldEnd()
            iprot.readStructEnd()
        finally:
            iprot.decrement_recursion_depth()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.increment_recursion_depth()
        try:
            oprot.writeStructBegin('submit_args')
            if self.readings is not None:
                oprot.writeFieldBegin('readings', TType.LIST, 1)
                oprot.writeListBegin(TType.STRUCT, len(self.readings))
                for iter22 in self.readings:
                    iter22.write(oprot)
                oprot.writeListEnd()
                oprot.writeFieldEnd()
            oprot.writeFieldStop()
            oprot.writeStructEnd()
        finally:
            oprot.decrement_recursion_depth()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(submit_args)
submit_args.thrift_spec = (
    None,  # 0
    (1, TType.LIST, 'readings', (TType.STRUCT, [Reading, None], False), None, ),  # 1
)


class submit_result(object):
    """
    Attributes:
     - success
     - invalid

    """
    thrift_spec = None


    def __init__(self, success = None, invalid = None,):
        self.success = success
        self.invalid = invalid

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.increment_recursion_depth()
        try:
            iprot.readStructBegin()
            while True:
                (fname, ftype, fid) = iprot.readFieldBegin()
                if ftype == TType.STOP:
                    break
                if fid == 0:
                    if ftype == TType.STRUCT:
                        self.success = Summary()
                        self.success.read(iprot)
                    else:
                        iprot.skip(ftype)
                elif fid == 1:
                    if ftype == TType.STRUCT:
                        self.invalid = InvalidReading.read(iprot)
                    else:
                        iprot.skip(ftype)
                else:
                    iprot.skip(ftype)
                iprot.readFieldEnd()
            iprot.readStructEnd()
        finally:
            iprot.decrement_recursion_depth()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.increment_recursion_depth()
        try:
            oprot.writeStructBegin('submit_result')
            if self.success is not None:
                oprot.writeFieldBegin('success', TType.STRUCT, 0)
                self.success.write(oprot)
                oprot.writeFieldEnd()
            if self.invalid is not None:
                oprot.writeFieldBegin('invalid', TType.STRUCT, 1)
                self.invalid.write(oprot)
                oprot.writeFieldEnd()
            oprot.writeFieldStop()
            oprot.writeStructEnd()
        finally:
            oprot.decrement_recursion_depth()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(submit_result)
submit_result.thrift_spec = (
    (0, TType.STRUCT, 'success', [Summary, None], None, ),  # 0
    (1, TType.STRUCT, 'invalid', [InvalidReading, None], None, ),  # 1
)
fix_spec(all_structs)
del all_structs
