#
# Autogenerated by Thrift Compiler (0.25.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys

from thrift.transport import TTransport
all_structs = []


class Reading(object):
    """
    Attributes:
     - sensor
     - taken_at_ms
     - celsius
     - samples
     - tags

    """
    thrift_spec = None


    def __init__(self, sensor = None, taken_at_ms = None, celsius = None, samples = None, tags = None,):
        self.sensor = sensor
        self.taken_at_ms = taken_at_ms
        self.celsius = celsius
        self.samples = samples
        self.tags = tags

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.increment_recursion_depth()
        try:
            iprot.readStructBegin()
            while True:
                (fname, ftype, fid) = iprot.readFieldBegin()
                if ftype == TType.STOP:
                    break
                if fid == 1:
                    if ftype == TType.STRING:
                        self.sensor = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                    else:
                        iprot.skip(ftype)
                elif fid == 2:
                    if ftype == TType.I64:
                        self.taken_at_ms = iprot.readI64()
                    else:
                        iprot.skip(ftype)
                elif fid == 3:
                    if ftype == TType.DOUBLE:
                        self.celsius = iprot.readDouble()
                    else:
                        iprot.skip(ftype)
                elif fid == 4:
                    if ftype == TType.LIST:
                        self.samples = []
                        (_etype3, _size0) = iprot.readListBegin()
                        for _i4 in range(_size0):
                            _elem5 = iprot.readDouble()
                            self.samples.append(_elem5)
                        iprot.readListEnd()
                    else:
                        iprot.skip(ftype)
                elif fid == 5:
                    if ftype == TType.MAP:
                        self.tags = {}
                        (_ktype7, _vtype8, _size6) = iprot.readMapBegin()
                        for _i10 in range(_size6):
                            _key11 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                            _val12 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                            self.tags[_key11] = _val12
                        iprot.readMapEnd()
                    else:
                        iprot.skip(ftype)
                else:
                    iprot.skip(ftype)
                iprot.readFieldEnd()
            iprot.readStructEnd()
        finally:
            iprot.decrement_recursion_depth()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.increment_recursion_depth()
        try:
            oprot.writeStructBegin('Reading')
            if self.sensor is not None:
                oprot.writeFieldBegin('sensor', TType.STRING, 1)
                oprot.writeString(self.sensor.encode('utf-8') if sys.version_info[0] == 2 else self.sensor)
                oprot.writeFieldEnd()
            if self.taken_at_ms is not None:
                oprot.writeFieldBegin('taken_at_ms', TType.I64, 2)
                oprot.writeI64(self.taken_at_ms)
                oprot.writeFieldEnd()
            if self.celsius is not None:
                oprot.writeFieldBegin('celsius', TType.DOUBLE, 3)
                oprot.writeDouble(self.celsius)
                oprot.writeFieldEnd()
            if self.samples is not None:
                oprot.writeFieldBegin('samples', TType.LIST, 4)
                oprot.writeListBegin(TType.DOUBLE, len(self.samples))
                for iter13 in self.samples:
                    oprot.writeDouble(iter13)
                oprot.writeListEnd()
                oprot.writeFieldEnd()
            if self.tags is not None:
                oprot.writeFieldBegin('tags', TType.MAP, 5)
                oprot.writeMapBegin(TType.STRING, TType.STRING, len(self.tags))
                for kiter14, viter15 in self.tags.items():
                    oprot.writeString(kiter14.encode('utf-8') if sys.version_info[0] == 2 else kiter14)
                    oprot.writeString(viter15.encode('utf-8') if sys.version_info[0] == 2 else viter15)
                oprot.writeMapEnd()
                oprot.writeFieldEnd()
            oprot.writeFieldStop()
            oprot.writeStructEnd()
        finally:
            oprot.decrement_recursion_depth()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class Summary(object):
    """
    Attributes:
     - count
     - mean_celsius
     - max_celsius
     - warmest_sensor

    """
    thrift_spec = None


    def __init__(self, count = None, mean_celsius = None, max_celsius = None, warmest_sensor = None,):
        self.count = count
        self.mean_celsius = mean_celsius
        self.max_celsius = max_celsius
        self.warmest_sensor = warmest_sensor

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.increment_recursion_depth()
        try:
            iprot.readStructBegin()
            while True:
                (fname, ftype, fid) = iprot.readFieldBegin()
                if ftype == TType.STOP:
                    break
                if fid == 1:
                    if ftype == TType.I32:
                        self.count = iprot.readI32()
                    else:
                        iprot.skip(ftype)
                elif fid == 2:
                    if ftype == TType.DOUBLE:
                        self.mean_celsius = iprot.readDouble()
                    else:
                        iprot.skip(ftype)
                elif fid == 3:
                    if ftype == TType.DOUBLE:
                        self.max_celsius = iprot.readDouble()
                    else:
                        iprot.skip(ftype)
                elif fid == 4:
                    if ftype == TType.STRING:
                        self.warmest_sensor = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                    else:
                        iprot.skip(ftype)
                else:
                    iprot.skip(ftype)
                iprot.readFieldEnd()
            iprot.readStructEnd()
        finally:
            iprot.decrement_recursion_depth()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.increment_recursion_depth()
        try:
            oprot.writeStructBegin('Summary')
            if self.count is not None:
                oprot.writeFieldBegin('count', TType.I32, 1)
                oprot.writeI32(self.count)
                oprot.writeFieldEnd()
            if self.mean_celsius is not None:
                oprot.writeFieldBegin('mean_celsius', TType.DOUBLE, 2)
                oprot.writeDouble(self.mean_celsius)
                oprot.writeFieldEnd()
            if self.max_celsius is not None:
                oprot.writeFieldBegin('max_celsius', TType.DOUBLE, 3)
                oprot.writeDouble(self.max_celsius)
                oprot.writeFieldEnd()
            if self.warmest_sensor is not None:
                oprot.writeFieldBegin('warmest_sensor', TType.STRING, 4)
                oprot.writeString(self.warmest_sensor.encode('utf-8') if sys.version_info[0] == 2 else self.warmest_sensor)
                oprot.writeFieldEnd()
            oprot.writeFieldStop()
            oprot.writeStructEnd()
        finally:
            oprot.decrement_recursion_depth()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class InvalidReading(TException):
    """
    Attributes:
     - sensor
     - reason

    """
    thrift_spec = None


    def __init__(self, sensor = None, reason = None,):
        super(InvalidReading, self).__setattr__('sensor', sensor)
        super(InvalidReading, self).__setattr__('reason', reason)

    def __setattr__(self, *args):
        raise TypeError("can't modify immutable instance")

    def __delattr__(self, *args):
        raise TypeError("can't modify immutable instance")

    def __hash__(self):
        return hash(self.__class__) ^ hash((self.sensor, self.reason, ))

    @classmethod
    def read(cls, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and cls.thrift_spec is not None:
            return iprot._fast_decode(None, iprot, [cls, cls.thrift_spec])
        iprot.increment_recursion_depth()
        try:
            iprot.readStructBegin()
            sensor = None
            reason = None
            while True:
                (fname, ftype, fid) = iprot.readFieldBegin()
                if ftype == TType.STOP:
                    break
                if fid == 1:
                    if ftype == TType.STRING:
                        sensor = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                    else:
                        iprot.skip(ftype)
                elif fid == 2:
                    if ftype == TType.STRING:
                        reason = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                    else:
                        iprot.skip(ftype)
                else:
                    iprot.skip(ftype)
                iprot.readFieldEnd()
            iprot.readStructEnd()
            return cls(
                sensor=sensor,
                reason=reason,
            )
        finally:
            iprot.decrement_recursion_depth()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.increment_recursion_depth()
        try:
            oprot.writeStructBegin('InvalidReading')
            if self.sensor is not None:
                oprot.writeFieldBegin('sensor', TType.STRING, 1)
                oprot.writeString(self.sensor.encode('utf-8') if sys.version_info[0] == 2 else self.sensor)
                oprot.writeFieldEnd()
            if self.reason is not None:
                oprot.writeFieldBegin('reason', TType.STRING, 2)
                oprot.writeString(self.reason.encode('utf-8') if sys.version_info[0] == 2 else self.reason)
                oprot.writeFieldEnd()
            oprot.writeFieldStop()
            oprot.writeStructEnd()
        finally:
            oprot.decrement_recursion_depth()

    def validate(self):
        return

    def __str__(self):
        return repr(self)

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(Reading)
Reading.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'sensor', 'UTF8', None, ),  # 1
    (2, TType.I64, 'taken_at_ms', None, None, ),  # 2
    (3, TType.DOUBLE, 'celsius', None, None, ),  # 3
    (4, TType.LIST, 'samples', (TType.DOUBLE, None, False), None, ),  # 4
    (5, TType.MAP, 'tags', (TType.STRING, 'UTF8', TType.STRING, 'UTF8', False), None, ),  # 5
)
all_structs.append(Summary)
Summary.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'count', None, None, ),  # 1
    (2, TType.DOUBLE, 'mean_celsius', None, None, ),  # 2
    (3, TType.DOUBLE, 'max_celsius', None, None, ),  # 3
    (4, TType.STRING, 'warmest_sensor', 'UTF8', None, ),  # 4
)
all_structs.append(InvalidReading)
InvalidReading.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'sensor', 'UTF8', None, ),  # 1
    (2, TType.STRING, 'reason', 'UTF8', None, ),  # 2
)
fix_spec(all_structs)
del all_structs
