{% set version = "1.0.1" %}

package:
  name: flet-libopaque
  version: '{{ version }}'

build:
  number: 1

source:
  url: https://github.com/stef/libopaque/archive/refs/tags/v{{ version }}.tar.gz

requirements:
  host:
    - flet-libsodium 1.0.20
    - flet-liboprf 0.5.0

patches:
  - mobile.patch