{% set version = "3.0.90" %}

package:
  name: flet-libjpeg
  version: '{{ version }}'

source:
  url: https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/{{ version }}/libjpeg-turbo-{{ version }}.tar.gz

build:
  number: 10

requirements:
  build:
    - cmake