{% set version = "3.13.1" %}

package:
  name: flet-libgdal
  version: '{{ version }}'

source:
  url: https://github.com/OSGeo/gdal/releases/download/v{{ version }}/gdal-{{ version }}.tar.gz

build:
  number: 1

requirements:
  build:
    - cmake
  host:
    - flet-libproj 9.5.0

patches:
  - mobile.patch
