package:
  name: cryptography
  version: 42.0.7

build:
  script_env:
    OPENSSL_STATIC: 1
    OPENSSL_DIR: '{platlib}/opt'

requirements:
  build:
    - setuptools_rust @ git+https://github.com/flet-dev/setuptools-rust@ios-support

  host:
    - cffi
    - openssl ^3.0.12
