package:
  name: cryptography
  version: 42.0.7

build:
  script_env:
    #OPENSSL_STATIC: 1
    OPENSSL_DIR: '{platlib}/opt'
    _PYTHON_SYSCONFIGDATA_NAME: '{sysconfigdata_name}'

requirements:
  host:
    - openssl ^3.0.12
