package:
  name: flet-libfreetype
  version: "2.13.3"

build:
  number: 10

source:
  url: https://downloads.sourceforge.net/project/freetype/freetype2/2.13.3/freetype-2.13.3.tar.gz

patches:
  - config.patch

about:
  license_file: docs/FTL.TXT
