package:
  name: fiona
  version: 1.10.1

requirements:
  host:
    - flet-libgdal 3.10.0

build:
  number: 4
  script_env:
    GDAL_VERSION: 3.10.0
    GDAL_LIB_PATH: '{platlib}/opt/lib'
    GDAL_INCLUDE_PATH: '{platlib}/opt/include'
    GDAL_LIBS: gdal
# {% if sdk != 'android' %}
    LDFLAGS: '-undefined dynamic_lookup'
# {% endif %}

patches:
  - mobile.patch