{% set version = "1.6.43" %}

package:
  name: flet-libpng
  version: '{{ version }}'

build:
  number: 10

source:
  url: https://github.com/pnggroup/libpng/archive/refs/tags/v{{ version }}.tar.gz

patches:
  - config.patch