package:
  name: contourpy
  version: 1.3.0

requirements:
  build:
    - ninja
    - cmake
  host:
    - pybind11

build:
  backend-args:
    - -Csetup-args=--cross-file
    - -Csetup-args={MESON_CROSS_FILE}