"""A million sensor readings kept in a DuckDB file on the phone, queried three ways."""

import os
import tempfile
import threading
import time

import duckdb
import flet as ft

STORAGE = os.getenv("FLET_APP_STORAGE_DATA", ".")
DB_PATH = os.path.join(STORAGE, "readings.duckdb")
PARQUET_PATH = os.path.join(STORAGE, "readings.parquet")
ROWS = 1_000_000

# Every mobile-specific setting belongs here rather than in a later SET, because the
# defaults are computed while the database is being constructed: memory_limit would
# otherwise come out as 80% of the device's *total* RAM, the spill directory would be
# `readings.duckdb.tmp` in app storage, and an unrecognised function name would send
# DuckDB to the network mid-query to fetch an extension that does not exist for Android.
con = duckdb.connect(
    DB_PATH,
    config={
        "memory_limit": "192MB",
        "threads": 2,
        "temp_directory": os.getenv("FLET_APP_STORAGE_TEMP", tempfile.gettempdir()),
        "autoinstall_known_extensions": False,
        "autoload_known_extensions": False,
    },
)

PLATFORM = con.execute("PRAGMA platform").fetchone()[0]
EXTENSIONS = ", ".join(
    name
    for (name,) in con.execute(
        "SELECT extension_name FROM duckdb_extensions() "
        "WHERE install_mode = 'STATICALLY_LINKED' ORDER BY 1"
    ).fetchall()
)
LIMIT, THREADS = con.execute(
    "SELECT current_setting('memory_limit'), current_setting('threads')"
).fetchone()

# Column aliases double as the table headers on screen, read back off con.description.
QUERIES = {
    "Devices": """
        SELECT device_id AS device, count(*) AS n, avg(celsius) AS mean,
               quantile_cont(celsius, 0.95) AS p95, max(celsius) - min(celsius) AS span
        FROM readings
        GROUP BY device_id
        ORDER BY p95 DESC
    """,
    "Smoothed": """
        SELECT device_id AS device, count(*) AS n,
               max(celsius) - min(celsius) AS raw,
               max(smoothed) - min(smoothed) AS smooth
        FROM (
            SELECT device_id, celsius,
                   avg(celsius) OVER (PARTITION BY device_id ORDER BY ts
                                      ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS smoothed
            FROM readings
        )
        GROUP BY device_id
        ORDER BY device
    """,
    # strftime() formats the bucket inside SQL, so a string crosses into Python. Nothing
    # in this app hands back a TIMESTAMP WITH TIME ZONE, which would need pytz — a module
    # the engine imports for those values and no dependency list installs.
    "Warmest": """
        SELECT strftime(date_trunc('hour', ts), '%b %d %H:00') AS hour, count(*) AS n,
               avg(celsius) AS mean, max(celsius) AS peak
        FROM readings
        GROUP BY hour
        ORDER BY mean DESC
        LIMIT 12
    """,
}


def ensure_readings():
    """Materialise the readings table on first launch, and return its row count.

    The million rows are generated by the engine out of `range(...)` and two
    trigonometric functions, so the app bundles no data file and downloads nothing,
    and every install holds byte-identical data. The table lives in the database
    file, so a relaunch finds it already there and this does nothing.
    """
    (exists,) = con.execute(
        "SELECT count(*) FROM duckdb_tables() WHERE table_name = 'readings'"
    ).fetchone()
    if not exists:
        con.execute(
            f"""
            CREATE TABLE readings AS
            SELECT (i % 12) AS device_id,
                   TIMESTAMP '2026-01-01 00:00:00' + INTERVAL (i) SECOND AS ts,
                   18 + (i % 12) * 0.25
                      + (5 + (i % 12) * 0.4) * sin(i / 900.0)
                      + 2 * cos(i / 37.0) AS celsius
            FROM range({ROWS}) AS t(i)
            """
        )
    return con.execute("SELECT count(*) FROM readings").fetchone()[0]


def cell(value):
    """Format one result value: counts with separators, measurements to two decimals."""
    if isinstance(value, int):
        return f"{value:,}"
    if isinstance(value, float):
        return f"{value:.2f}"
    return str(value)


def line(*cells):
    """One row of the results table: a wide first column, then a column per value."""
    return ft.Row(
        controls=[
            ft.Text(cells[0], expand=3),
            *(ft.Text(c, expand=2) for c in cells[1:]),
        ]
    )


def main(page: ft.Page):
    """Three analytical queries over the stored million rows, plus a Parquet export.

    The header is the engine describing itself: the platform string DuckDB reports —
    which is what its extension repository is keyed on, and which says `osx_arm64` on
    an iPhone — the extensions compiled into this wheel, and the limits the connection
    was opened with.
    """
    busy = threading.Lock()

    def start(worker):
        """Disable the controls, then run `worker` on Flet's thread pool.

        Disabling the buttons does not by itself prevent an overlap: `run_thread` submits
        to a shared pool, so a tap already in flight when the disable goes out still
        arrives. And an overlap does not raise — the result slot belongs to the connection,
        so the second `execute` replaces the one the first is about to read and its
        `fetchone()` comes back either empty or holding the other query's answer. The lock
        is what makes the extra tap a no-op; a `con.cursor()` per thread is the other way.
        """
        if not busy.acquire(blocking=False):
            return

        def guard():
            """Refresh the count, run the worker, and report whatever it raised.

            The wrapper is not decoration: `page.run_thread` never retrieves the worker's
            future, so anything raised in there is discarded silently — a cancelled query
            above all, which is a normal outcome here rather than a bug, and an
            `OutOfMemoryException` from a query the memory limit could not hold. Counting
            first builds the table on a first launch, and rebuilds it after one the user
            cancelled halfway, which would otherwise leave every query failing on a
            missing table. Clearing the table on the way out matters as much as the
            message: numbers from the previous run under a fresh error read as current.
            """
            try:
                caption.value = f"{ensure_readings():,} readings stored"
                worker()
            except duckdb.InterruptException:
                results.controls = []
                footer.value = "cancelled"
            except Exception as error:
                results.controls = []
                footer.value = str(error)
            finally:
                picker.disabled = False
                exporter.disabled = False
                cancel.disabled = True
                spinner.visible = False
                busy.release()
                page.update()  # auto-update does not reach background threads

        picker.disabled = True
        exporter.disabled = True
        cancel.disabled = False
        spinner.visible = True
        page.update()
        page.run_thread(guard)

    def query():
        """Time the selected query and lay its rows out, headers included."""
        started = time.perf_counter()
        rows = con.execute(QUERIES[picker.selected[0]]).fetchall()
        elapsed = (time.perf_counter() - started) * 1000.0
        results.controls = [
            line(*(column[0] for column in con.description)),
            ft.Divider(height=1),
            *(line(*(cell(value) for value in row)) for row in rows),
        ]
        footer.value = f"{len(rows)} rows in {elapsed:.0f} ms"

    def dump():
        """Write the whole table out as Parquet, then read the file back.

        The round trip is the point: this is the one package on the index that can
        write Parquet, so what lands in app storage is a file other tools can open.
        Counting rows out of it costs almost nothing, because that answer is in the
        footer of the file rather than in its data.
        """
        started = time.perf_counter()
        # USE_TMP_FILE writes beside the target and renames only on success. Without it
        # the first export, cancelled or killed part-way, leaves a footer-less
        # readings.parquet that read_parquet rejects with "No magic bytes found at end
        # of file" — indistinguishable on disk from an export that finished.
        con.execute(
            f"COPY readings TO '{PARQUET_PATH}' "
            "(FORMAT PARQUET, COMPRESSION zstd, USE_TMP_FILE true)"
        )
        written = (time.perf_counter() - started) * 1000.0

        started = time.perf_counter()
        rows, mean = con.execute(
            f"SELECT count(*), avg(celsius) FROM read_parquet('{PARQUET_PATH}')"
        ).fetchone()
        read = (time.perf_counter() - started) * 1000.0

        footer.value = (
            f"{rows:,} rows to {os.path.getsize(PARQUET_PATH) / 1e6:.1f} MB of zstd "
            f"Parquet in {written:.0f} ms; read back and averaged ({mean:.2f} °C) in "
            f"{read:.0f} ms; database file {os.path.getsize(DB_PATH) / 1e6:.1f} MB"
        )

    def pick():
        """Run whichever query the segmented button was just switched to."""
        start(query)

    def export():
        """Send the Parquet round trip off the UI thread."""
        start(dump)

    def stop():
        """Abort whatever is running; the worker then raises InterruptException."""
        con.interrupt()

    page.appbar = ft.AppBar(title=ft.Text("duckdb readings"), center_title=True)
    page.add(
        ft.SafeArea(
            expand=True,
            content=ft.Column(
                scroll=ft.ScrollMode.AUTO,
                controls=[
                    ft.Text(
                        f"duckdb {duckdb.__version__} on {PLATFORM} — {EXTENSIONS} "
                        f"linked in — {LIMIT} limit, {THREADS} threads",
                        size=12,
                    ),
                    ft.Row(
                        controls=[
                            caption := ft.Text(expand=True),
                            spinner := ft.ProgressRing(
                                width=16, height=16, visible=False
                            ),
                        ]
                    ),
                    picker := ft.SegmentedButton(
                        segments=[
                            ft.Segment(value=name, label=ft.Text(name))
                            for name in QUERIES
                        ],
                        selected=[next(iter(QUERIES))],
                        show_selected_icon=False,
                        on_change=pick,
                    ),
                    ft.Row(
                        controls=[
                            exporter := ft.Button(
                                "Export Parquet",
                                icon=ft.Icons.SAVE_ALT,
                                on_click=export,
                            ),
                            cancel := ft.Button("Cancel", disabled=True, on_click=stop),
                        ]
                    ),
                    results := ft.Column(spacing=4),
                    footer := ft.Text(size=11),
                ],
            ),
        )
    )

    start(query)


if __name__ == "__main__":
    ft.run(main)
