"""A million sensor readings kept in a DuckDB file on the phone, queried three ways."""

import os
import tempfile
import time

import duckdb

STORAGE = os.getenv("FLET_APP_STORAGE_DATA", ".")
DB_PATH = os.path.join(STORAGE, "readings.duckdb")
PARQUET_PATH = os.path.join(STORAGE, "readings.parquet")
ROWS = 1_000_000

# Every mobile-specific setting belongs here rather than in a later SET, because the
# defaults are computed while the database is being constructed: memory_limit would
# otherwise come out as 80% of the device's *total* RAM, the spill directory would be
# readings.duckdb.tmp in app storage, and an unrecognised function name would send
# DuckDB to the network mid-query to fetch an extension that does not exist for Android.
con = duckdb.connect(
    DB_PATH,
    config={
        "memory_limit": "192MB",
        "threads": 2,
        "temp_directory": os.getenv("FLET_APP_STORAGE_TEMP", tempfile.gettempdir()),
        "autoinstall_known_extensions": False,
        "autoload_known_extensions": False,
    },
)

# Raised in the worker thread when cancel() interrupts a running query. Re-exported so
# the UI layer never has to import duckdb itself.
Cancelled = duckdb.InterruptException

# Column aliases double as the table headers on screen, read back off con.description.
QUERIES = {
    "Devices": """
        SELECT device_id AS device, count(*) AS n, avg(celsius) AS mean,
               quantile_cont(celsius, 0.95) AS p95, max(celsius) - min(celsius) AS span
        FROM readings
        GROUP BY device_id
        ORDER BY p95 DESC
    """,
    "Smoothed": """
        SELECT device_id AS device, count(*) AS n,
               max(celsius) - min(celsius) AS raw,
               max(smoothed) - min(smoothed) AS smooth
        FROM (
            SELECT device_id, celsius,
                   avg(celsius) OVER (PARTITION BY device_id ORDER BY ts
                                      ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS smoothed
            FROM readings
        )
        GROUP BY device_id
        ORDER BY device
    """,
    # strftime() formats the bucket inside SQL, so a string crosses into Python. Nothing
    # in this app hands back a TIMESTAMP WITH TIME ZONE, which would need pytz — a module
    # the engine imports for those values and no dependency list installs.
    "Warmest": """
        SELECT strftime(date_trunc('hour', ts), '%b %d %H:00') AS hour, count(*) AS n,
               avg(celsius) AS mean, max(celsius) AS peak
        FROM readings
        GROUP BY hour
        ORDER BY mean DESC
        LIMIT 12
    """,
}


def describe_engine():
    """Ask the engine to describe itself, as the one line under the app bar.

    Worth printing on a device: the platform string is what DuckDB's extension
    repository is keyed on, and it answers `osx_arm64` on an iPhone and
    `linux_i686_android` on 32-bit ARM.
    """
    (platform,) = con.execute("PRAGMA platform").fetchone()
    extensions = ", ".join(
        name
        for (name,) in con.execute(
            "SELECT extension_name FROM duckdb_extensions() "
            "WHERE install_mode = 'STATICALLY_LINKED' ORDER BY 1"
        ).fetchall()
    )
    limit, threads = con.execute(
        "SELECT current_setting('memory_limit'), current_setting('threads')"
    ).fetchone()
    return (
        f"duckdb {duckdb.__version__} on {platform} — {extensions} linked in — "
        f"{limit} limit, {threads} threads"
    )


def ensure_readings():
    """Materialise the readings table on first launch, and return its row count.

    The million rows are generated by the engine out of `range(...)` and two
    trigonometric functions, so the app bundles no data file and downloads nothing,
    and every install holds byte-identical data. The table lives in the database
    file, so a relaunch finds it already there and this does nothing.
    """
    (exists,) = con.execute(
        "SELECT count(*) FROM duckdb_tables() WHERE table_name = 'readings'"
    ).fetchone()
    if not exists:
        con.execute(
            f"""
            CREATE TABLE readings AS
            SELECT (i % 12) AS device_id,
                   TIMESTAMP '2026-01-01 00:00:00' + INTERVAL (i) SECOND AS ts,
                   18 + (i % 12) * 0.25
                      + (5 + (i % 12) * 0.4) * sin(i / 900.0)
                      + 2 * cos(i / 37.0) AS celsius
            FROM range({ROWS}) AS t(i)
            """
        )
    return con.execute("SELECT count(*) FROM readings").fetchone()[0]


def run_query(name):
    """Run one of QUERIES; return its column headers, its rows and the milliseconds.

    The headers come off `con.description` rather than being written out again, so
    editing a query's aliases relabels the table on screen.
    """
    started = time.perf_counter()
    rows = con.execute(QUERIES[name]).fetchall()
    headers = [column[0] for column in con.description]
    return headers, rows, (time.perf_counter() - started) * 1000.0


def export_parquet():
    """Write the whole table out as Parquet, read it back, and return the numbers.

    The round trip is the point: this is the package on the index that can write
    Parquet, so what lands in app storage is a file other tools can open. Counting
    rows back out of it costs almost nothing, because that answer sits in the file's
    footer rather than in its data.
    """
    started = time.perf_counter()
    # USE_TMP_FILE writes beside the target and renames only on success. Without it an
    # export cancelled or killed part-way leaves a footer-less readings.parquet that
    # read_parquet rejects with "No magic bytes found at end of file" —
    # indistinguishable on disk from an export that finished.
    con.execute(
        f"COPY readings TO '{PARQUET_PATH}' "
        "(FORMAT PARQUET, COMPRESSION zstd, USE_TMP_FILE true)"
    )
    written = (time.perf_counter() - started) * 1000.0

    started = time.perf_counter()
    rows, mean = con.execute(
        f"SELECT count(*), avg(celsius) FROM read_parquet('{PARQUET_PATH}')"
    ).fetchone()
    read = (time.perf_counter() - started) * 1000.0

    return {
        "rows": rows,
        "mean": mean,
        "written_ms": written,
        "read_ms": read,
        "parquet_mb": os.path.getsize(PARQUET_PATH) / 1e6,
        "db_mb": os.path.getsize(DB_PATH) / 1e6,
    }


def cancel():
    """Abort whatever query is running; its own thread then raises Cancelled."""
    con.interrupt()
