{% set version = "0.2.5" %}

package:
  name: flet-libyaml
  version: '{{ version }}'

build:
  number: 10

source:
  url: https://github.com/yaml/libyaml/releases/download/{{ version }}/yaml-{{ version }}.tar.gz
