package:
  name: pandas
  version: 2.2.2

requirements:
  build:
    - ninja
  host:
    - numpy ^2.0.0

patches:
  - mobile.patch

build:
  backend-args:
    - -Csetup-args=--cross-file
    - -Csetup-args={MESON_CROSS_FILE}