package:
  name: pandas
  version: 2.2.2

requirements:
  build:
    - meson
    - ninja
  host:
    - numpy 2.0.0

build:
  backend-args:
    - -Csetup-args=--cross-file
    - -Csetup-args={MESON_CROSS_FILE}