{% set version = "8.11.0" %}

package:
  name: flet-libcurl
  version: '{{ version }}'

source:
  url: https://curl.se/download/curl-{{ version }}.tar.gz

build:
  number: 1

requirements:
  host:
    - openssl 3.0.15
    - flet-libpsl 0.21.5