package:
  name: pyproj
  version: 3.7.0

build:
  script_env:
    PROJ_VERSION: 9.5.0
    PROJ_DIR: '{platlib}/opt'
# {% if sdk != 'android' %}
    LDFLAGS: '-undefined dynamic_lookup'
# {% endif %}

requirements:
  host:
    - flet-libproj 9.5.0

patches:
  - mobile.patch